"""Initial migration with all TDM models

Revision ID: aec55a121109
Revises: 
Create Date: 2026-02-23 12:25:30.711536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aec55a121109'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_string_encrypted', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('connection_string_encrypted', sa.Text(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineage',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemas',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_connection_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'version_number', name='uq_schema_version')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('schema_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('path_prefix', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masking_rules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('schema_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pii_classification',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('pii_type', sa.String(length=100), nullable=False),
    sa.Column('technique', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_version_id', 'table_name', 'column_name', name='uq_pii_sv_table_column')
    )
    op.create_table('tables',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['schema_version_id'], ['schema_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_version_id', 'schema_name', 'name', name='uq_tables_sv_schema_name')
    )
    op.create_table('columns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('inferred_type', sa.String(length=100), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=True),
    sa.Column('ordinal_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='uq_columns_table_name')
    )
    op.create_table('dataset_metadata',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('meta_key', sa.String(length=255), nullable=False),
    sa.Column('meta_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'meta_key', name='uq_dataset_metadata_dv_key')
    )
    op.create_table('relationships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('child_table_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('parent_column_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('child_column_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['child_column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['child_table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['parent_column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['parent_table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('dataset_metadata')
    op.drop_table('columns')
    op.drop_table('tables')
    op.drop_table('pii_classification')
    op.drop_table('masking_rules')
    op.drop_table('dataset_versions')
    op.drop_table('schema_versions')
    op.drop_table('schemas')
    op.drop_table('lineage')
    op.drop_table('job_logs')
    op.drop_table('jobs')
    op.drop_table('environments')
    op.drop_table('connections')
    # ### end Alembic commands ###
